### ISSUE TITLE
Install setcap prior to Caddy install

### ISSUE THREAD

**Issue by Nixtren** [sayem314/Caddy-Web-Server-Installer#11]
Ubuntu 14.04

If you install Caddy without installing PHP, Caddy won't be able to bind to port 80/443 because the following command was not successfully executed:
`setcap cap_net_bind_service=+ep $caddypath/caddy`

The solution is to run the following command before running setcap:
`apt-get install libcap2-bin -y`

**Comment by sayem314** [comment]
I've found this working on almost all OS, still I'll add this command :)

Edit: pull #11 committed https://github.com/sayem314/Caddy-Web-Server-Installer/commit/f2588d0bf883d8542be7614e9d487034e7abd107

**Comment by Nixtren** [comment]
Yeah I was also expecting this to work on all OS, but looks like I caught a server without it installed and setcap was silently failing. I have a feeling issue #6 is this issue, I got the exact message, but now it's solved :)

Thanks!
