### ISSUE TITLE
Ubuntu 16.04 Install error

### ISSUE THREAD

**Issue by onenewnet** [sayem314/Caddy-Web-Server-Installer#13]
```
           .....
           ......
```

find: ‘/var/lib/lxcfs/cgroup/memory/system.slice/run-lxcfs-controllers-cpuset.mount/cgroup.event_control’: Permission denied
find: ‘/var/lib/lxcfs/cgroup/memory/system.slice/ntp.service/memory.pressure_level’: Permission denied
find: ‘/var/lib/lxcfs/cgroup/memory/system.slice/ntp.service/memory.force_empty’: Permission denied
find: ‘/var/lib/lxcfs/cgroup/memory/system.slice/ntp.service/cgroup.event_control’: Permission denied
find: ‘/var/lib/lxcfs/cgroup/memory/system.slice/systemd-update-utmp.service/memory.pressure_level’: Permission denied
find: ‘/var/lib/lxcfs/cgroup/memory/system.slice/systemd-update-utmp.service/memory.force_empty’: Permission denied
find: ‘/var/lib/lxcfs/cgroup/memory/system.slice/systemd-update-utmp.service/cgroup.event_control’: Permission denied
find: ‘/var/lib/lxcfs/cgroup/memory/system.slice/lxcfs.service/memory.pressure_level’: Permission denied
find: ‘/var/lib/lxcfs/cgroup/memory/system.slice/lxcfs.service/memory.force_empty’: Permission denied
find: ‘/var/lib/lxcfs/cgroup/memory/system.slice/lxcfs.service/cgroup.event_control’: Permission denied

```
              .....
               .....
```

**Comment by sayem314** [comment]
Thanks. This has been fixed on v3.9 :)
