### ISSUE TITLE
use caddyplug

### ISSUE THREAD

**Issue by zuohuadong** [sayem314/Caddy-Web-Server-Installer#21]
https://caddyserver.com/products/licenses

we can use :+1: 
https://github.com/abiosoft/caddyplug

**Comment by sayem314** [comment]
Any plugin that is available on [caddy download page](https://caddyserver.com/download) can be installed without any problem :) There is no need for script update!

**Comment by zuohuadong** [comment]
Not commercially available

**Comment by sayem314** [comment]
Sorry! My script is only designed to pull plugins from caddy official site. Caddyplug author should publish the plugin on caddyserver.com. [This tutorial](https://github.com/mholt/caddy/wiki/Publishing-a-Plugin-to-the-Download-Page) shows the process of publishing a plugin.

**Comment by zuohuadong** [comment]
Caddyserver is a commercial website that offers a fee for caddy and does not provide such plug-ins.
If you use Caddyserver on the server you have to pay.
Do you understand?

**Comment by zuohuadong** [comment]
But if you compile from the source, you just have to follow the Apache license without paying.

**Comment by mholt** [comment]
@zuohuadong 

> If you use Caddyserver on the server you have to pay. Do you understand?

Sorry, but that's simply not correct. You can use Caddy binaries for free for any non-commercial / personal-use sites. You only need to purchase a license if you use official binaries for commercial/business purposes. That's clearly spelled out right on the licenses page:

> The personal license is appropriate for academic research, personal projects, websites that aren't for profit, and development at home.

I hope that clears things up. :)

**Comment by zuohuadong** [comment]
@mholt  I know.

In most cases, I will caddy commercial. I tried to convince the rest of the company that Caddy was easy to use, but only caddyserver easy to use.


I hope the Caddy application will be more extensive, especially in the commercial field instead of Nginx.
However, if as open source software, more complex than Nginx, then, I still choose Nginx.


Can caddyserver consider other business models? For example, the provision of Third-party Plug-ins platform, charge a certain fee.

**Comment by mholt** [comment]
> Can caddyserver consider other business models?

Yes, we're already working on it. If telemetry is successful, we may be able to do away with paid licenses.

**Comment by zuohuadong** [comment]
@mholt 
What can I do for you? 
I really like Git,cors,ssl...

I am trying to translate the Chinese document.

**Comment by mholt** [comment]
@zuohuadong Thanks, that's really nice! I also would like to see the docs translated into Chinese, but unfortunately I don't have a way to host them on my site right now, nor the time to allocate to make it happen. Do you think they could be hosted as Markdown documents or something simple and I could link people there? (We should chat about this on the Caddy repo if you want to continue.)
