### ISSUE TITLE
Looks shell doesnt work on lastest Caddy

### ISSUE THREAD

**Issue by singhigh** [sayem314/Caddy-Web-Server-Installer#22]
Looks shell doesnt work on lastest Caddy )

**Comment by sayem314** [comment]
Sorry 😐 What do you mean actually? Can you please elaborate?

**Comment by revunix** [comment]
Hey,

same here... 

```
 Done. Caddy has been installed :)
   Run caddy start to start Caddy Web Server
 
 root@netcup:~# caddy start
   Starting Caddy Web Server...  [DONE]
 
   Caddy Web Server is NOT running
```


it won't be start 😭 

i'm on newest Debian.

**Comment by sayem314** [comment]
@revunix I will deploy a latest droplet over DigitalOcean and take a look.

**Comment by revunix** [comment]
Okay thanks 🙂 
i hope you can reproduce the issue.

**Comment by revunix** [comment]
CentOS is also broken...
its a fresh install.

```
[root@centos ~]# caddy start
  Starting Caddy Web Server...Redirecting to /bin/systemctl start caddy.service
  [DONE]

  Caddy Web Server is NOT running
```

```
[root@centos ~]# lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.4.1708 (Core)
Release:	7.4.1708
Codename:	Core
```

**Comment by sayem314** [comment]
Hey @revunix, I’ve tested the script on latest Debian (9.4 x64) and everything seems to be working fine. See: http://167.99.217.152 and http://167.99.217.152/info.php

Maybe something wrong with your OS template. Which provider are you using btw?

**Comment by revunix** [comment]
I tried on many OS versions, even the newest ubuntu form original site. Have a KVM so i can use what i wont... but isn't working...

what iso do you use? i'm on netcup servers and there have pretty good templates.

btw. can you please support freebsd? ❤️

**Comment by sayem314** [comment]
I’m not using any custom templates. I use VPS from DigitalOcean/Vultr for testing out stuff. About FreeBSD, I’m actually not into *BSD stuff.

**Comment by spekulatius** [comment]
I've tried to use your install script @sayem314 on a scaleway Ubuntu 16.04 fresh install and got the same issue. Any suggestions for this?
