### ISSUE TITLE
Can't update Caddyserver

### ISSUE THREAD

**Issue by craigary** [sayem314/Caddy-Web-Server-Installer#30]
Hi, I love your script but there's a problem when updating the Caddyserver.

When I run `caddy update`, it says "Looks like you already have latest version installed. Abort." which is not.

Then I run `caddy version`, here is the info:

>   Caddy Web Server v1.0.0
  Caddy Web Server Installer - v6.2
  PHP 7.3.9-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Sep  2 2019 12:54:24) ( NTS )

Currently the latest version of Caddy Web Server is v1.0.3. So is there any way to work around? Thank You!

**Comment by sayem314** [comment]
I will take a look. Thanks!

**Comment by sayem314** [comment]
Updated. Update your script re-run the update command. Close this issue if it's fixed.

**Comment by craigary** [comment]
Problem solved, Thank you!
