### ISSUE TITLE
Does this script support Caddy 2 beta?

### ISSUE THREAD

**Issue by craigary** [sayem314/Caddy-Web-Server-Installer#32]
Hi, I've been using Caddy-Web-Server-Installer for a while and very happy with it. But I wonder does it support CaddyServer 2? 

Caddy 2 is still in beta, but it's fine for me to use it in my personal project, I tried to set it up manually, it's pretty good.

Also, Caddy 2 is listed on Digital Ocean for one-click install, I think it's pretty stable and it's time to implement it.

Thank you~

**Comment by sayem314** [comment]
Not yet but once Caddy 2 is released under stable branch it should just work fine.

**Comment by craigary** [comment]
Thank you. I'll wait till Caddy 2 release.
