### ISSUE TITLE
wget don't support "--show-progress"

### ISSUE THREAD

**Issue by flyhigao** [sayem314/Caddy-Web-Server-Installer#33]
[root@fileserver /]# uname -a
Linux fileserver 5.3.18-2-pve #1 SMP PVE 5.3.18-2 (Sat, 15 Feb 2020 15:11:52 +0100) x86_64 x86_64 x86_64 GNU/Linux
[root@fileserver /]# cat /etc/redhat-release 
CentOS Linux release 7.7.1908 (Core)

wget don't support "--show-progress"

**Comment by sayem314** [comment]
Fixed on v6.6
