### ISSUE TITLE
ARM should be fine

### ISSUE THREAD

**Issue by mholt** [sayem314/Caddy-Web-Server-Installer#5]
In [these lines](https://github.com/sayem314/Caddy-Web-Server-Installer/blob/7dd8892f1cf17c75ce634ae88abed245eeb68ba1/caddy#L120-L125) it looks like you abort an install (and updates in another part of the script) if the system is ARM architecture.

Caddy can run on ARM. Take a quick gander at how the script at https://getcaddy.com/ handles it; it even compiles for ARM versions 5, 6, and 7.

**Comment by sayem314** [comment]
Thank you. I'll work on that, I'm traveling now ;)

**Comment by sayem314** [comment]
Added support for ARM install/update
