### ISSUE TITLE
Add ability to skip PHP installation

### ISSUE THREAD

**Issue by Nixtren** [sayem314/Caddy-Web-Server-Installer#7]
Hi,

I think we should add an option to skip PHP installation. In my personal case I want to use PHP 7, so it would be great if I could manually install PHP 7 (fpm) and then run this Caddy installer without worrying about it installing PHP 5.

For the time being I can edit the script to remove the PHP install commands, but it would be better to add an option or something :)

**Comment by sayem314** [comment]
Thanks, will work on that :)

**Comment by sayem314** [comment]
Done :)

**Comment by Nixtren** [comment]
Thanks :)

What's the fix you perform on the PHP configuration files? You change PHP to run on Caddy's user/group?
